---
- hosts: localhost
  tasks:
    - name: getting secrets
      shell: git clone "https://{{ github_user }}:{{ github_token }}@github.com/Devi0138/Master_secret.git" "vars/"
      ignore_errors: yes
    - include_vars:
          file: secret.yml
          name: secrets
      no_log: true
